export { Tooth } from './Tooth'
export { Crown } from './Crown'
export { Bridge } from './Bridge'
export { Veneer } from './Veneer'
export { Implant } from './Implant'
export { Lab } from './Lab'
export { WhatsAppIcon } from './WhatsAppIcon'
export { Sun } from './Sun'
export { Moon } from './Moon'
export { Menu } from './Menu'
export { Close } from './Close'
export { Pin } from './Pin'
export { Phone } from './Phone'
export { Mail } from './Mail'
export { CheckCircle } from './CheckCircle'
export { Cycle } from './Cycle'
export type { IconProps } from './types'
